apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: staging-hub-flapi-frontend-cert
  namespace: staging-hub-flapi-frontend
spec:
  secretName: staging-hub-flapi-frontend-tls
  dnsNames:
    - staging.hub.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
