apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prod-hub-flapi-crzcommon-cert
  namespace: prod-hub-flapi-frontend
spec:
  secretName: prod-hub-flapi-frontend-crzcommon-tls
  dnsNames:
    - hub.flapi.org
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
