apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-hub-flapi-frontend-hpa
  namespace: prod-hub-flapi-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-hub-flapi-frontend-deployment
  minReplicas: 5
  maxReplicas: 15
  targetCPUUtilizationPercentage: 70
