/* tslint:disable */
/* eslint-disable */
/**
 * Flapi Hub API
 * Documentation Swagger auto-générée.
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from './configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig, AxiosResponse } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common'
import type { RequestArgs } from './base'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base'

/**
 * AwsDomainResponse (Interface)
 * @export
 * @interface AwsDomainResponse
 */
export interface AwsDomainResponse {
  /**
   *
   * @type {boolean}
   * @memberof AwsDomainResponse
   */
  subdomainExist: boolean
}
/**
 * BadRequestResponse (Interface)
 * @export
 * @interface BadRequestResponse
 */
export interface BadRequestResponse {
  /**
   *
   * @type {string}
   * @memberof BadRequestResponse
   */
  code: string
  /**
   *
   * @type {string}
   * @memberof BadRequestResponse
   */
  message: string
}
/**
 * BadValidationRequestResponse (Interface)
 * @export
 * @interface BadValidationRequestResponse
 */
export interface BadValidationRequestResponse {
  /**
   *
   * @type {string}
   * @memberof BadValidationRequestResponse
   */
  code: string
  /**
   *
   * @type {Array<string>}
   * @memberof BadValidationRequestResponse
   */
  messages: Array<string>
}
/**
 * Bucket (Model)
 * @export
 * @interface Bucket
 */
export interface Bucket {
  /**
   *
   * @type {number}
   * @memberof Bucket
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof Bucket
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof Bucket
   */
  visibility?: string
  /**
   *
   * @type {string}
   * @memberof Bucket
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof Bucket
   */
  updated_at?: string
}
/**
 * checkDomainAvailabilityValidator (Validator)
 * @export
 * @interface CheckDomainAvailabilityValidator
 */
export interface CheckDomainAvailabilityValidator {
  /**
   *
   * @type {string}
   * @memberof CheckDomainAvailabilityValidator
   */
  domain: string
}
/**
 * CheckSessionValidityResponse (Interface)
 * @export
 * @interface CheckSessionValidityResponse
 */
export interface CheckSessionValidityResponse {
  /**
   *
   * @type {boolean}
   * @memberof CheckSessionValidityResponse
   */
  valid: boolean
  /**
   *
   * @type {string}
   * @memberof CheckSessionValidityResponse
   */
  error?: string
}
/**
 * checkSubDomainAvailabilityValidator (Validator)
 * @export
 * @interface CheckSubDomainAvailabilityValidator
 */
export interface CheckSubDomainAvailabilityValidator {
  /**
   *
   * @type {string}
   * @memberof CheckSubDomainAvailabilityValidator
   */
  subdomain: string
}
/**
 * createNewApplicationValidator (Validator)
 * @export
 * @interface CreateNewApplicationValidator
 */
export interface CreateNewApplicationValidator {
  /**
   *
   * @type {string}
   * @memberof CreateNewApplicationValidator
   */
  customerName: string
  /**
   *
   * @type {string}
   * @memberof CreateNewApplicationValidator
   */
  projectName: string
  /**
   *
   * @type {string}
   * @memberof CreateNewApplicationValidator
   */
  fullDomain: string
  /**
   *
   * @type {string}
   * @memberof CreateNewApplicationValidator
   */
  categoryApp: string
  /**
   *
   * @type {string}
   * @memberof CreateNewApplicationValidator
   */
  longDescriptionApp: string
  /**
   *
   * @type {string}
   * @memberof CreateNewApplicationValidator
   */
  shortDescriptionApp: string
}
/**
 * Database (Model)
 * @export
 * @interface Database
 */
export interface Database {
  /**
   *
   * @type {number}
   * @memberof Database
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof Database
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof Database
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof Database
   */
  updated_at?: string
}
/**
 * getAuthenticatedUserErrorResponse (Interface)
 * @export
 * @interface GetAuthenticatedUserErrorResponse
 */
export interface GetAuthenticatedUserErrorResponse {
  /**
   *
   * @type {string}
   * @memberof GetAuthenticatedUserErrorResponse
   */
  error: string
}
/**
 * HealthCheckDebugInfo (Interface)
 * @export
 * @interface HealthCheckDebugInfo
 */
export interface HealthCheckDebugInfo {
  /**
   *
   * @type {number}
   * @memberof HealthCheckDebugInfo
   */
  pid: number
  /**
   *
   * @type {number}
   * @memberof HealthCheckDebugInfo
   */
  ppid?: number
  /**
   *
   * @type {number}
   * @memberof HealthCheckDebugInfo
   */
  uptime: number
  /**
   *
   * @type {string}
   * @memberof HealthCheckDebugInfo
   */
  version: string
  /**
   *
   * @type {string}
   * @memberof HealthCheckDebugInfo
   */
  platform: string
}
/**
 * HealthCheckItem (Interface)
 * @export
 * @interface HealthCheckItem
 */
export interface HealthCheckItem {
  /**
   *
   * @type {boolean}
   * @memberof HealthCheckItem
   */
  isCached: boolean
  /**
   *
   * @type {string}
   * @memberof HealthCheckItem
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof HealthCheckItem
   */
  message: string
  /**
   *
   * @type {string}
   * @memberof HealthCheckItem
   */
  status: string
}
/**
 * HealthCheckReport (Interface)
 * @export
 * @interface HealthCheckReport
 */
export interface HealthCheckReport {
  /**
   *
   * @type {boolean}
   * @memberof HealthCheckReport
   */
  isHealthy: boolean
  /**
   *
   * @type {string}
   * @memberof HealthCheckReport
   */
  status: string
  /**
   *
   * @type {string}
   * @memberof HealthCheckReport
   */
  finishedAt: string
  /**
   *
   * @type {HealthCheckDebugInfo}
   * @memberof HealthCheckReport
   */
  debugInfo: HealthCheckDebugInfo
  /**
   *
   * @type {Array<HealthCheckItem>}
   * @memberof HealthCheckReport
   */
  checks: Array<HealthCheckItem>
}
/**
 * LoginSuccessResponse (Interface)
 * @export
 * @interface LoginSuccessResponse
 */
export interface LoginSuccessResponse {
  /**
   *
   * @type {string}
   * @memberof LoginSuccessResponse
   */
  token: string
  /**
   *
   * @type {string}
   * @memberof LoginSuccessResponse
   */
  type: string
  /**
   *
   * @type {string}
   * @memberof LoginSuccessResponse
   */
  expiresAt: string
}
/**
 * loginValidator (Validator)
 * @export
 * @interface LoginValidator
 */
export interface LoginValidator {
  /**
   *
   * @type {string}
   * @memberof LoginValidator
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof LoginValidator
   */
  password: string
}
/**
 * MessageResponse (Interface)
 * @export
 * @interface MessageResponse
 */
export interface MessageResponse {
  /**
   *
   * @type {string}
   * @memberof MessageResponse
   */
  message: string
}
/**
 * File (Model)
 * @export
 * @interface ModelFile
 */
export interface ModelFile {
  /**
   *
   * @type {number}
   * @memberof ModelFile
   */
  id?: number
  /**
   *
   * @type {number}
   * @memberof ModelFile
   */
  bucket_id?: number
  /**
   *
   * @type {Bucket}
   * @memberof ModelFile
   */
  bucket?: Bucket
  /**
   *
   * @type {string}
   * @memberof ModelFile
   */
  pathfilename?: string
  /**
   *
   * @type {string}
   * @memberof ModelFile
   */
  url?: string
  /**
   *
   * @type {number}
   * @memberof ModelFile
   */
  size?: number
  /**
   *
   * @type {string}
   * @memberof ModelFile
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof ModelFile
   */
  updated_at?: string
}
/**
 *
 * @export
 * @interface PaginationMeta
 */
export interface PaginationMeta {
  /**
   *
   * @type {number}
   * @memberof PaginationMeta
   */
  total?: number
  /**
   *
   * @type {number}
   * @memberof PaginationMeta
   */
  page?: number
  /**
   *
   * @type {number}
   * @memberof PaginationMeta
   */
  perPage?: number
  /**
   *
   * @type {number}
   * @memberof PaginationMeta
   */
  currentPage?: number
  /**
   *
   * @type {number}
   * @memberof PaginationMeta
   */
  lastPage?: number
  /**
   *
   * @type {number}
   * @memberof PaginationMeta
   */
  firstPage?: number
  /**
   *
   * @type {string}
   * @memberof PaginationMeta
   */
  lastPageUrl?: string
  /**
   *
   * @type {string}
   * @memberof PaginationMeta
   */
  firstPageUrl?: string
  /**
   *
   * @type {string}
   * @memberof PaginationMeta
   */
  nextPageUrl?: string
  /**
   *
   * @type {string}
   * @memberof PaginationMeta
   */
  previousPageUrl?: string
}
/**
 * Project (Model)
 * @export
 * @interface Project
 */
export interface Project {
  /**
   *
   * @type {number}
   * @memberof Project
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof Project
   */
  application_name?: string
  /**
   *
   * @type {number}
   * @memberof Project
   */
  user_id?: number
  /**
   *
   * @type {User}
   * @memberof Project
   */
  user?: User
  /**
   *
   * @type {string}
   * @memberof Project
   */
  domain_name?: string
  /**
   *
   * @type {number}
   * @memberof Project
   */
  file_id?: number
  /**
   *
   * @type {any}
   * @memberof Project
   */
  file?: any
  /**
   *
   * @type {number}
   * @memberof Project
   */
  database_id?: number
  /**
   *
   * @type {Database}
   * @memberof Project
   */
  database?: Database
  /**
   *
   * @type {string}
   * @memberof Project
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof Project
   */
  updated_at?: string
}
/**
 * ResultMessageResponse (Interface)
 * @export
 * @interface ResultMessageResponse
 */
export interface ResultMessageResponse {
  /**
   *
   * @type {boolean}
   * @memberof ResultMessageResponse
   */
  success: boolean
  /**
   *
   * @type {string}
   * @memberof ResultMessageResponse
   */
  message: string
}
/**
 * SignUpPayload (Interface)
 * @export
 * @interface SignUpPayload
 */
export interface SignUpPayload {
  /**
   *
   * @type {string}
   * @memberof SignUpPayload
   */
  lastname: string
  /**
   *
   * @type {string}
   * @memberof SignUpPayload
   */
  firstname: string
  /**
   *
   * @type {string}
   * @memberof SignUpPayload
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof SignUpPayload
   */
  password: string
  /**
   *
   * @type {string}
   * @memberof SignUpPayload
   */
  password_confirmation: string
}
/**
 * User (Model)
 * @export
 * @interface User
 */
export interface User {
  /**
   *
   * @type {number}
   * @memberof User
   */
  id: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  keycloak_user_id?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  role_id?: number
  /**
   *
   * @type {UserRole}
   * @memberof User
   */
  role: UserRole
  /**
   *
   * @type {string}
   * @memberof User
   */
  lastname: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  firstname: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  currency_code?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  ip_address?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  ip_region?: string
  /**
   *
   * @type {number}
   * @memberof User
   */
  stripe_customer_id?: number
  /**
   *
   * @type {string}
   * @memberof User
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof User
   */
  updated_at?: string
}
/**
 * UserRole (Model)
 * @export
 * @interface UserRole
 */
export interface UserRole {
  /**
   *
   * @type {number}
   * @memberof UserRole
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof UserRole
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof UserRole
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof UserRole
   */
  updated_at?: string
}
/**
 * UserSession (Model)
 * @export
 * @interface UserSession
 */
export interface UserSession {
  /**
   *
   * @type {number}
   * @memberof UserSession
   */
  id?: number
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  issuer?: string
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  redirect_uri?: string
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  session_state?: string
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  type?: string
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  access_token?: string
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  refresh_token?: string
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  expires_at?: string
  /**
   *
   * @type {number}
   * @memberof UserSession
   */
  user_id?: number
  /**
   *
   * @type {User}
   * @memberof UserSession
   */
  user?: User
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof UserSession
   */
  updated_at?: string
}
/**
 * ValidationError (Interface)
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  message: string
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  rule: string
  /**
   *
   * @type {string}
   * @memberof ValidationError
   */
  field: string
}
/**
 * ValidationErrorResponse (Interface)
 * @export
 * @interface ValidationErrorResponse
 */
export interface ValidationErrorResponse {
  /**
   *
   * @type {ValidationError}
   * @memberof ValidationErrorResponse
   */
  errors: ValidationError
}

/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Returns **200** (OK) as **application/json**   _app/controllers/auth_controller.ts_ - **checkSessionIsValid**
     * @summary Vérifie si la session utilisateur est valide (checkSessionIsValid)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkSessionIsValid: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/auth/check-session`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Retourne les informations de l\'utilisateur connecté à partir du token fourni.   _app/controllers/auth_controller.ts_ - **getAuthenticatedUser**
     * @summary Récupère l\'utilisateur authentifié (getAuthenticatedUser)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthenticatedUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/auth/user`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Permet à un utilisateur de se déconnecter   _app/controllers/auth_controller.ts_ - **signOut**
     * @summary Déconnexion d\'un utilisateur (signOut)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signOut: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/auth/signout`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Returns **201** (Created) as **application/json**   _app/controllers/auth_controller.ts_ - **signUp**
     * @summary Inscription d\'un utilisateur (signUp)
     * @param {SignUpPayload} [signUpPayload]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signUp: async (signUpPayload?: SignUpPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/auth/signup`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(signUpPayload, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Permet à un utilisateur de se connecter   _app/controllers/auth_controller.ts_ - **signinCallback**
     * @summary Connexion d\'un utilisateur (signinCallback)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signinCallback: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/auth/signin-callback`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
  return {
    /**
     * Returns **200** (OK) as **application/json**   _app/controllers/auth_controller.ts_ - **checkSessionIsValid**
     * @summary Vérifie si la session utilisateur est valide (checkSessionIsValid)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async checkSessionIsValid(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CheckSessionValidityResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.checkSessionIsValid(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AuthApi.checkSessionIsValid']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Retourne les informations de l\'utilisateur connecté à partir du token fourni.   _app/controllers/auth_controller.ts_ - **getAuthenticatedUser**
     * @summary Récupère l\'utilisateur authentifié (getAuthenticatedUser)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getAuthenticatedUser(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthenticatedUser(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AuthApi.getAuthenticatedUser']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Permet à un utilisateur de se déconnecter   _app/controllers/auth_controller.ts_ - **signOut**
     * @summary Déconnexion d\'un utilisateur (signOut)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async signOut(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.signOut(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath = operationServerMap['AuthApi.signOut']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Returns **201** (Created) as **application/json**   _app/controllers/auth_controller.ts_ - **signUp**
     * @summary Inscription d\'un utilisateur (signUp)
     * @param {SignUpPayload} [signUpPayload]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async signUp(
      signUpPayload?: SignUpPayload,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.signUp(signUpPayload, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath = operationServerMap['AuthApi.signUp']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Permet à un utilisateur de se connecter   _app/controllers/auth_controller.ts_ - **signinCallback**
     * @summary Connexion d\'un utilisateur (signinCallback)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async signinCallback(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.signinCallback(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AuthApi.signinCallback']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = AuthApiFp(configuration)
  return {
    /**
     * Returns **200** (OK) as **application/json**   _app/controllers/auth_controller.ts_ - **checkSessionIsValid**
     * @summary Vérifie si la session utilisateur est valide (checkSessionIsValid)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkSessionIsValid(options?: RawAxiosRequestConfig): AxiosPromise<CheckSessionValidityResponse> {
      return localVarFp.checkSessionIsValid(options).then((request) => request(axios, basePath))
    },
    /**
     * Retourne les informations de l\'utilisateur connecté à partir du token fourni.   _app/controllers/auth_controller.ts_ - **getAuthenticatedUser**
     * @summary Récupère l\'utilisateur authentifié (getAuthenticatedUser)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuthenticatedUser(options?: RawAxiosRequestConfig): AxiosPromise<User> {
      return localVarFp.getAuthenticatedUser(options).then((request) => request(axios, basePath))
    },
    /**
     * Permet à un utilisateur de se déconnecter   _app/controllers/auth_controller.ts_ - **signOut**
     * @summary Déconnexion d\'un utilisateur (signOut)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signOut(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
      return localVarFp.signOut(options).then((request) => request(axios, basePath))
    },
    /**
     * Returns **201** (Created) as **application/json**   _app/controllers/auth_controller.ts_ - **signUp**
     * @summary Inscription d\'un utilisateur (signUp)
     * @param {SignUpPayload} [signUpPayload]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signUp(signUpPayload?: SignUpPayload, options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
      return localVarFp.signUp(signUpPayload, options).then((request) => request(axios, basePath))
    },
    /**
     * Permet à un utilisateur de se connecter   _app/controllers/auth_controller.ts_ - **signinCallback**
     * @summary Connexion d\'un utilisateur (signinCallback)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    signinCallback(options?: RawAxiosRequestConfig): AxiosPromise<MessageResponse> {
      return localVarFp.signinCallback(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi {
  /**
   * Returns **200** (OK) as **application/json**   _app/controllers/auth_controller.ts_ - **checkSessionIsValid**
   * @summary Vérifie si la session utilisateur est valide (checkSessionIsValid)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public static async checkSessionIsValid(
    options?: RawAxiosRequestConfig,
  ): Promise<AxiosResponse<CheckSessionValidityResponse, any>> {
    const localVarAxiosArgs = await AuthApiAxiosParamCreator().checkSessionIsValid(options)
    return globalAxios.request<CheckSessionValidityResponse>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }

  /**
   * Retourne les informations de l\'utilisateur connecté à partir du token fourni.   _app/controllers/auth_controller.ts_ - **getAuthenticatedUser**
   * @summary Récupère l\'utilisateur authentifié (getAuthenticatedUser)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public static async getAuthenticatedUser(options?: RawAxiosRequestConfig): Promise<AxiosResponse<User, any>> {
    const localVarAxiosArgs = await AuthApiAxiosParamCreator().getAuthenticatedUser(options)
    return globalAxios.request<User>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }

  /**
   * Permet à un utilisateur de se déconnecter   _app/controllers/auth_controller.ts_ - **signOut**
   * @summary Déconnexion d\'un utilisateur (signOut)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public static async signOut(options?: RawAxiosRequestConfig): Promise<AxiosResponse<MessageResponse, any>> {
    const localVarAxiosArgs = await AuthApiAxiosParamCreator().signOut(options)
    return globalAxios.request<MessageResponse>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }

  /**
   * Returns **201** (Created) as **application/json**   _app/controllers/auth_controller.ts_ - **signUp**
   * @summary Inscription d\'un utilisateur (signUp)
   * @param {SignUpPayload} [signUpPayload]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public static async signUp(
    signUpPayload?: SignUpPayload,
    options?: RawAxiosRequestConfig,
  ): Promise<AxiosResponse<MessageResponse, any>> {
    const localVarAxiosArgs = await AuthApiAxiosParamCreator().signUp(signUpPayload, options)
    return globalAxios.request<MessageResponse>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }

  /**
   * Permet à un utilisateur de se connecter   _app/controllers/auth_controller.ts_ - **signinCallback**
   * @summary Connexion d\'un utilisateur (signinCallback)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AuthApi
   */
  public static async signinCallback(options?: RawAxiosRequestConfig): Promise<AxiosResponse<MessageResponse, any>> {
    const localVarAxiosArgs = await AuthApiAxiosParamCreator().signinCallback(options)
    return globalAxios.request<MessageResponse>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }
}

/**
 * AwsDomainApi - axios parameter creator
 * @export
 */
export const AwsDomainApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Vérifie si un domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkDomainAvailability**
     * @summary Vérifie la disponibilité d\'un domaine (checkDomainAvailability)
     * @param {CheckDomainAvailabilityValidator} [checkDomainAvailabilityValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkDomainAvailability: async (
      checkDomainAvailabilityValidator?: CheckDomainAvailabilityValidator,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/aws/domain/check`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        checkDomainAvailabilityValidator,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Vérifie si un sous-domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkSubDomainAvailability**
     * @summary Vérifie la disponibilité d\'un sous-domaine (checkSubDomainAvailability)
     * @param {CheckSubDomainAvailabilityValidator} [checkSubDomainAvailabilityValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkSubDomainAvailability: async (
      checkSubDomainAvailabilityValidator?: CheckSubDomainAvailabilityValidator,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/aws/subdomain/check`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        checkSubDomainAvailabilityValidator,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * AwsDomainApi - functional programming interface
 * @export
 */
export const AwsDomainApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = AwsDomainApiAxiosParamCreator(configuration)
  return {
    /**
     * Vérifie si un domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkDomainAvailability**
     * @summary Vérifie la disponibilité d\'un domaine (checkDomainAvailability)
     * @param {CheckDomainAvailabilityValidator} [checkDomainAvailabilityValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async checkDomainAvailability(
      checkDomainAvailabilityValidator?: CheckDomainAvailabilityValidator,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AwsDomainResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.checkDomainAvailability(
        checkDomainAvailabilityValidator,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AwsDomainApi.checkDomainAvailability']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Vérifie si un sous-domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkSubDomainAvailability**
     * @summary Vérifie la disponibilité d\'un sous-domaine (checkSubDomainAvailability)
     * @param {CheckSubDomainAvailabilityValidator} [checkSubDomainAvailabilityValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async checkSubDomainAvailability(
      checkSubDomainAvailabilityValidator?: CheckSubDomainAvailabilityValidator,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AwsDomainResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.checkSubDomainAvailability(
        checkSubDomainAvailabilityValidator,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['AwsDomainApi.checkSubDomainAvailability']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * AwsDomainApi - factory interface
 * @export
 */
export const AwsDomainApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = AwsDomainApiFp(configuration)
  return {
    /**
     * Vérifie si un domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkDomainAvailability**
     * @summary Vérifie la disponibilité d\'un domaine (checkDomainAvailability)
     * @param {CheckDomainAvailabilityValidator} [checkDomainAvailabilityValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkDomainAvailability(
      checkDomainAvailabilityValidator?: CheckDomainAvailabilityValidator,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AwsDomainResponse> {
      return localVarFp
        .checkDomainAvailability(checkDomainAvailabilityValidator, options)
        .then((request) => request(axios, basePath))
    },
    /**
     * Vérifie si un sous-domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkSubDomainAvailability**
     * @summary Vérifie la disponibilité d\'un sous-domaine (checkSubDomainAvailability)
     * @param {CheckSubDomainAvailabilityValidator} [checkSubDomainAvailabilityValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    checkSubDomainAvailability(
      checkSubDomainAvailabilityValidator?: CheckSubDomainAvailabilityValidator,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<AwsDomainResponse> {
      return localVarFp
        .checkSubDomainAvailability(checkSubDomainAvailabilityValidator, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * AwsDomainApi - object-oriented interface
 * @export
 * @class AwsDomainApi
 * @extends {BaseAPI}
 */
export class AwsDomainApi {
  /**
   * Vérifie si un domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkDomainAvailability**
   * @summary Vérifie la disponibilité d\'un domaine (checkDomainAvailability)
   * @param {CheckDomainAvailabilityValidator} [checkDomainAvailabilityValidator]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AwsDomainApi
   */
  public static async checkDomainAvailability(
    checkDomainAvailabilityValidator?: CheckDomainAvailabilityValidator,
    options?: RawAxiosRequestConfig,
  ): Promise<AxiosResponse<AwsDomainResponse, any>> {
    const localVarAxiosArgs = await AwsDomainApiAxiosParamCreator().checkDomainAvailability(
      checkDomainAvailabilityValidator,
      options,
    )
    return globalAxios.request<AwsDomainResponse>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }

  /**
   * Vérifie si un sous-domaine est disponible via AWS Route 53 Domains   _app/controllers/aws_domain_controller.ts_ - **checkSubDomainAvailability**
   * @summary Vérifie la disponibilité d\'un sous-domaine (checkSubDomainAvailability)
   * @param {CheckSubDomainAvailabilityValidator} [checkSubDomainAvailabilityValidator]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof AwsDomainApi
   */
  public static async checkSubDomainAvailability(
    checkSubDomainAvailabilityValidator?: CheckSubDomainAvailabilityValidator,
    options?: RawAxiosRequestConfig,
  ): Promise<AxiosResponse<AwsDomainResponse, any>> {
    const localVarAxiosArgs = await AwsDomainApiAxiosParamCreator().checkSubDomainAvailability(
      checkSubDomainAvailabilityValidator,
      options,
    )
    return globalAxios.request<AwsDomainResponse>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }
}

/**
 * ClientApi - axios parameter creator
 * @export
 */
export const ClientApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Returns **201** (Created) as **application/json**   _app/controllers/client_controller.ts_ - **createNewApplication**
     * @summary Créer une nouvelle application (createNewApplication)
     * @param {CreateNewApplicationValidator} [createNewApplicationValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewApplication: async (
      createNewApplicationValidator?: CreateNewApplicationValidator,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/client/app/create`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        createNewApplicationValidator,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * ClientApi - functional programming interface
 * @export
 */
export const ClientApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ClientApiAxiosParamCreator(configuration)
  return {
    /**
     * Returns **201** (Created) as **application/json**   _app/controllers/client_controller.ts_ - **createNewApplication**
     * @summary Créer une nouvelle application (createNewApplication)
     * @param {CreateNewApplicationValidator} [createNewApplicationValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createNewApplication(
      createNewApplicationValidator?: CreateNewApplicationValidator,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultMessageResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createNewApplication(
        createNewApplicationValidator,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ClientApi.createNewApplication']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * ClientApi - factory interface
 * @export
 */
export const ClientApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = ClientApiFp(configuration)
  return {
    /**
     * Returns **201** (Created) as **application/json**   _app/controllers/client_controller.ts_ - **createNewApplication**
     * @summary Créer une nouvelle application (createNewApplication)
     * @param {CreateNewApplicationValidator} [createNewApplicationValidator]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNewApplication(
      createNewApplicationValidator?: CreateNewApplicationValidator,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ResultMessageResponse> {
      return localVarFp
        .createNewApplication(createNewApplicationValidator, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * ClientApi - object-oriented interface
 * @export
 * @class ClientApi
 * @extends {BaseAPI}
 */
export class ClientApi {
  /**
   * Returns **201** (Created) as **application/json**   _app/controllers/client_controller.ts_ - **createNewApplication**
   * @summary Créer une nouvelle application (createNewApplication)
   * @param {CreateNewApplicationValidator} [createNewApplicationValidator]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ClientApi
   */
  public static async createNewApplication(
    createNewApplicationValidator?: CreateNewApplicationValidator,
    options?: RawAxiosRequestConfig,
  ): Promise<AxiosResponse<ResultMessageResponse, any>> {
    const localVarAxiosArgs = await ClientApiAxiosParamCreator().createNewApplication(
      createNewApplicationValidator,
      options,
    )
    return globalAxios.request<ResultMessageResponse>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }
}

/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * The application is healthy   _app/controllers/health_controller.ts_ - **health**
     * @summary Check the health of the application (health)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    health: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      const localVarPath = `/health`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
  return {
    /**
     * The application is healthy   _app/controllers/health_controller.ts_ - **health**
     * @summary Check the health of the application (health)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async health(
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthCheckReport>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.health(options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['HealthApi.health']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = HealthApiFp(configuration)
  return {
    /**
     * The application is healthy   _app/controllers/health_controller.ts_ - **health**
     * @summary Check the health of the application (health)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    health(options?: RawAxiosRequestConfig): AxiosPromise<HealthCheckReport> {
      return localVarFp.health(options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi {
  /**
   * The application is healthy   _app/controllers/health_controller.ts_ - **health**
   * @summary Check the health of the application (health)
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof HealthApi
   */
  public static async health(options?: RawAxiosRequestConfig): Promise<AxiosResponse<HealthCheckReport, any>> {
    const localVarAxiosArgs = await HealthApiAxiosParamCreator().health(options)
    return globalAxios.request<HealthCheckReport>({
      ...localVarAxiosArgs.options,
      url: BASE_PATH + localVarAxiosArgs.url,
    })
  }
}
